### ISSUE TITLE
ovnkube: sync: When a node is deleted from the cluster, the chassis record for it remains stale

### ISSUE THREAD

**Issue by abhat** [ovn-org/ovn-kubernetes#1105]
When a node is deprovisioned/deleted from the cluster, the southbound db's chassis record for this node doesn't get deleted. This results in stale geneve tunnels and vswitchd flows on the other nodes in the cluster. At scale, this can mean thousands of tunnels and unused stale flows.

**Comment by russellb** [comment]
Just some more detail ... ovn-controller will delete its associated `Chassis` record if it shuts down gracefully.  I'm not sure that's ever the case, though.  The fallback is that something else needs to do the cleanup.  ovn-kubernetes is already watching Nodes, so it can add this as another thing it does when syncing Nodes or when it sees a Node get deleted.

This will require knowing which `Chassis` record in the ovn southbound database corresponds to a Node.  ovn-kubernetes already ensures that the `hostname` field of the `Chassis` is equal to the `Node` `name`.

**Comment by girishmg** [comment]
@russellb @abhat @dcbw  we faced this issue, and we tried to fix this in several ways (that I have captured below) and none of them worked. We resorted to using a script that either the deployer or a K8s CNI operator runs manually after deleting the node from the cluster. Normally, they will need to
1. cordon the node
2. drain the node
3. delete the node from the k8s cluster
4. run `kubeadm reset` on the node
5. run the script, that essentially calls `ovn-sbctl chassis-del hostname`

Things I tried:

1. On the ovnkube-master daemon, I tried adding code in Node delete handler that will delete the chassis from the OVN SB. The ovnkube-master already knows the chassis Id of the node since it is in the Node annotation. The issue with this was that if the `ovn-controller` is still running on the node, then it sees that the chassis is missing in the OVN SB and it will add it back. So, this will not work.

2. You cannot use the preStop hook for the ovn-controller container since ovn-controller will add the entry back.

3. On the ovnkube-node daemon, we tried to trap  SIGTERM and then in the function callback handler for the trap delete the chassis. However, this didn't work since `kubelet` doesn't send SIGTERM for the system daemons and daemonset. It just sends SIGKILL.

The only time `kubelet` sends SIGTERM for ovnkube-node daemon is when you do
`kubelet delete -f ovnkube-node.yaml`. For only this case, the chassis entry gets deleted.

4. There is `ovs-appctl -t ovn-controller exit` command that should delete the entry from SB. However, there is no hook for us to call this because of SIGKILL being sent instead of SIGTERM.

**Comment by danwinship** [comment]
>     2\. You cannot use the preStop hook for the ovn-controller container since ovn-controller will add the entry back.

Can't you just have the "pre stop" hook actually stop ovn-controller?

**Comment by girishmg** [comment]
> > ```
> > 2\. You cannot use the preStop hook for the ovn-controller container since ovn-controller will add the entry back.
> > ```
> 
> 
> Can't you just have the "pre stop" hook actually stop ovn-controller?

@danwinship the issue with this is that the preStop hook container is a synchronous call. When the ovn-controller is killed, ovnkube.sh sees that the PID is gone and it restarts the ovn-controller again. Off course, we could teach ovnkube.sh not to do that for certain cases by touching a file somewhere and checking for the existence of that file.

AFAIR, the bigger issue is that, preStop hook will not get called when you do `kubectl delete node` (please check since it has been long time). It only gets called on `kubectl delete pod -n onv-kubernetes ovnkube-node-asdfasd` or `kubectl delete -f ovnkube-node.yaml`. It doesn't get called when someone just does `kubeadm reset -f` on that node (and yes I agree that they should be punished for that, so this use case we can ignore)

**Comment by abhat** [comment]
> The issue with this was that if the `ovn-controller` is still running on the node, then it sees that the chassis is missing in the OVN SB and it will add it back. So, this will not work.
 
Why would the ovn-controller be still running on the node? Also, the syncNodes will not have this node in the list only when the API server deletes the node object. Will that not happen after the node is shut down?

**Comment by abhat** [comment]
I guess the ordering is not guaranteed is what you are saying. 

Initial stab at fixing the issue: https://github.com/ovn-org/ovn-kubernetes/pull/1113

**Comment by abhat** [comment]
Fixed by #1113
