### ISSUE TITLE
figure out why we're skipping some tests

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#1316]
#1311 adds comments to `test/scripts/e2e-kind.sh` to indicate why certain tests are being skipped, but no one immediately remembers why a few of them are skipped so they're just in a `???` section at the end. Someone should figure out what's up with them, and file issues if they indicate bugs or missing features in ovn-kubernetes (or link to existing issues if they already exist)

**Comment by trozet** [comment]
List of cases that were being skipped due to failures:
[sig-network] NoSNAT [Feature:NoSNAT] [Slow] [It] Should be able to send traffic between Pods without SNAT

[sig-network] Services [It] should have session affinity work for LoadBalancer service with ESIPP off [Slow] [DisabledForLargeClusters]
[sig-network] Services [It] should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters]
[sig-network] Services [It] should have session affinity work for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters]
[sig-network] Services [It] should be able to switch session affinity for LoadBalancer service with ESIPP off [Slow] [DisabledForLargeClusters]

[sig-network] DNS configMap nameserver [Feature:Networking-IPv6] [LinuxOnly]
Change stubDomain [It] should be able to change stubDomain configuration [Slow][Serial]
Forward PTR lookup [It] should forward PTR records lookup to upstream nameserver [Slow][Serial]
Forward external name lookup [It] should forward externalname lookup to upstream nameserver [Slow][Serial]
[sig-network] DNS configMap nameserver [IPv4]
Forward external name lookup [It] should forward externalname lookup to upstream nameserver [Slow][Serial]
Forward PTR lookup [It] should forward PTR records lookup to upstream nameserver [Slow][Serial]

**Comment by tssurya** [comment]
As part of update to kube v1.23.1, the following tests are failing:

```
HostPort:
[sig-network] SCTP [LinuxOnly] [It] should create a Pod with SCTP HostPort
[sig-network] HostPort [It] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]
DNS:
[sig-network] Networking [It] should provider Internet connection for containers using DNS [Feature:Networking-DNS]

Network Policies:
[sig-network] Netpol NetworkPolicy between server and client should allow ingress access from updated namespace [Feature:NetworkPolicy]
[sig-network] Netpol NetworkPolicy between server and client should enforce egress policy allowing traffic to a server in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]
[sig-network] NetworkPolicyLegacy [LinuxOnly] NetworkPolicy between server and client should enforce policy to allow traffic only from a different namespace, based on NamespaceSelector [Feature:NetworkPolicy]
[sig-network] NetworkPolicyLegacy [LinuxOnly] NetworkPolicy between server and client should enforce policies to check ingress and egress policies can be controlled independently based on PodSelector [Feature:NetworkPolicy]
```

Flaky ones:
```
A set of valid responses are returned for both pod and service Proxy
```
