### ISSUE TITLE
Add e2e test for IPv4/IPv6 multicast snooping/relay

### ISSUE THREAD

**Issue by dceara** [ovn-org/ovn-kubernetes#1704]
Currently there's no e2e test for namespace IPv4/IPv6 multicast pod to pod traffic. Having a test that brings up a couple of pods and makes sure that multicast traffic flows properly when `k8s.ovn.org/multicast-enabled=true` would be nice.

**Comment by danwinship** [comment]
Downstream (currently openshift-sdn-only) test: https://github.com/openshift/origin/blob/master/test/extended/networking/multicast.go

It makes use of [this image](https://github.com/openshift/test-multicast/blob/master/image/Dockerfile) because there weren't any other images available that had any tools in them that seemed useful for testing multicast.

**Comment by dceara** [comment]
@danwinship Thanks! This would be ideal for ovn-kubernetes too. I'll try to adapt this and pull it in the upstream e2e ov-kubernetes tests.

**Comment by dceara** [comment]
We actually have these tests now (for a while): https://github.com/ovn-org/ovn-kubernetes/blob/master/test/e2e/multicast.go

Closing.
