### ISSUE TITLE
Fix scaling of SNAT entries with egress gw

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#1794]
With egress gw and enabling SNAT, we create a SNAT entry per pod, whether it is an egress gw pod or a regular pod. This creates a lot of entries. One way to cut down on this is by making a single SNAT entry for all non-egress gw pods (cluster ip subnet as is done previous to egress gw). This works because OVN does longest prefix match even for SNAT entries

**Comment by alexanderConstantinescu** [comment]
Turns out this is not an issue. We actually perform this operation here: https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/gateway_init.go#L308-L330 . I created a kind cluster and launched the e2e test called `Should validate connectivity to the vxlan interface simulating an external gateway and validate traffic was encapsulated` the only SNAT entries found on the GR (while that test was executing) were the following:

```
ovn-nbctl --db tcp:172.21.0.2:6641 lr-nat-list GR_ovn-worker
TYPE             EXTERNAL_IP        EXTERNAL_PORT    LOGICAL_IP            EXTERNAL_MAC         LOGICAL_PORT
snat             172.21.0.3                          10.244.0.0/16
```
