### ISSUE TITLE
Service/Endpoint code cleanup

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#1828]
In services.go and endpoints.go there's a lot of duplication of code. There looks to be some room for code improvement by breaking things up into functions.

**Comment by trozet** [comment]
I just remembered @aojea is already working on refactoring some of this stuff I think so assigning to him

**Comment by aojea** [comment]
This is a great idea

I think that my PR can serve as example on the directions.

I think this is a good exercise for new contributors to get used with the codebase

**Comment by kedark3** [comment]
@aojea in your comment you mention `my PR can serve as example on the directions.` can you please link your PR? I see one PR linked by Tim #1818 . I'm trying to understand the project and since I found this issue with help wanted, I'd like to see if I can do any exercise that can contribute to project and help me improve my understanding. Thank you.

**Comment by trozet** [comment]
Just a note we are goign to be removing the old services and endpoints code in favor of the new k8s controller that @aojea added:
https://github.com/ovn-org/ovn-kubernetes/pull/2033

So I'm not sure how applicable this github issue is anymore.

**Comment by kedark3** [comment]
@trozet ack. Is there anything else that can serve as a good 1st PR and guide for newbies?

**Comment by aojea** [comment]
> Just a note we are goign to be removing the old services and endpoints code in favor of the new k8s controller that @aojea added:
> #2033
> 
> So I'm not sure how applicable this github issue is anymore.

This seems no longer needed, since I'm assigned, I think that is fair if I close it :)
