### ISSUE TITLE
After restart a VM with OVNk kind deployment there is no connectivity to ovn-control-plane (the Master node)

### ISSUE THREAD

**Issue by roytman** [ovn-org/ovn-kubernetes#2020]
When a VM with OVNk `kind` deployment is restarted, `kube-apiserver` is not reachable.

A  possible issue is in network interfaces configuration of the `ovn-control-plane` docker container, which contains the K8s Master node. Despite that `eth0` was enslaved by ovs-system, it continues to hold the external IP address. 

**Before reboot:**
3: br-int: <BROADCAST,MULTICAST> mtu 1400 qdisc noop state DOWN group default qlen 1000
    link/ether e2:30:c5:01:ef:62 brd ff:ff:ff:ff:ff:ff
4: genev_sys_6081: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65000 qdisc noqueue master ovs-system state UNKNOWN group default qlen 1000
    link/ether aa:e5:df:47:11:b9 brd ff:ff:ff:ff:ff:ff
5: ovn-k8s-mp0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 56:86:0d:30:bf:60 brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.2/24 brd 10.244.1.255 scope global ovn-k8s-mp0
       valid_lft forever preferred_lft forever
6: **breth0**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff
    inet **172.18.0.3/16** brd 172.18.255.255 scope global breth0
       valid_lft forever preferred_lft forever
7: br-local: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether b6:69:2e:05:a2:40 brd ff:ff:ff:ff:ff:ff
8: ovn-k8s-gw0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 0a:58:a9:fe:00:01 brd ff:ff:ff:ff:ff:ff
    inet 169.254.0.1/20 brd 169.254.15.255 scope global ovn-k8s-gw0
       valid_lft forever preferred_lft forever
9: 3bf4e07e6790931@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP group default 
    link/ether 16:de:ae:3f:9e:8a brd ff:ff:ff:ff:ff:ff link-netns cni-f12abb99-d716-8b92-687d-eb1ee961820e
13: **eth0@if14**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ovs-system state UP group default 
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fc00:f853:ccd:e793::3/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:3/64 scope link 
       valid_lft forever preferred_lft forever

**and after reboot:**
6: ovn-k8s-gw0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 0a:58:a9:fe:00:01 brd ff:ff:ff:ff:ff:ff
    inet 169.254.0.1/20 brd 169.254.15.255 scope global ovn-k8s-gw0
       valid_lft forever preferred_lft forever
7: br-local: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 9e:ad:30:cd:f8:46 brd ff:ff:ff:ff:ff:ff
8: **breth0**: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff
9: **eth0@if10**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ovs-system state UP group default 
    link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet **172.18.0.4/16** brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fc00:f853:ccd:e793::4/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:4/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by andreaskaris** [comment]
Workaround:
~~~
for n in $(kind get  nodes  --name ovn) ; do 
  docker exec "$n" /bin/bash -c 'cid=$(crictl ps | awk "/ovnkube-node/ {print \$1}"); crictl exec $cid ovn-kube-util nics-to-bridge eth0'
done
~~~

More details: running `ovn-kube-util nics-to-bridge eth0` inside the ovnkube-node containers rewired the networking correctly.
~~~
[root@ovn-control-plane ~]# ovn-kube-util nics-to-bridge eth0
I0706 16:39:35.081799   26987 ovs.go:96] Maximum command line arguments set to: 191102
I0706 16:39:35.096918   26987 nicstobridge.go:220] Successfully created OVS bridge "breth0"
W0706 16:39:35.097052   26987 nicstobridge.go:170] Failed to parse file /etc/default/openvswitch (open /etc/default/openvswitch: no such file or directory)
I0706 16:39:35.097665   26987 nicstobridge.go:90] Successfully saved addr "172.18.0.4/16 breth0" to newLink "breth0"
I0706 16:39:35.097774   26987 nicstobridge.go:90] Successfully saved addr "fc00:f853:ccd:e793::4/64 breth0" to newLink "breth0"
I0706 16:39:35.097903   26987 nicstobridge.go:112] Successfully saved route "{Ifindex: 8 Dst: 172.18.0.0/16 Src: 172.18.0.4 Gw: <nil> Flags: [] Table: 254}"
I0706 16:39:35.097950   26987 nicstobridge.go:112] Successfully saved route "{Ifindex: 8 Dst: fc00:f853:ccd:e793::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254}"
I0706 16:39:35.098017   26987 nicstobridge.go:112] Successfully saved route "{Ifindex: 8 Dst: <nil> Src: <nil> Gw: 172.18.0.1 Flags: [] Table: 254}"
I0706 16:39:35.098073   26987 nicstobridge.go:112] Successfully saved route "{Ifindex: 8 Dst: <nil> Src: <nil> Gw: fc00:f853:ccd:e793::1 Flags: [] Table: 254}"
[root@ovn-control-plane ~]# ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether c2:3c:52:44:04:d9 brd ff:ff:ff:ff:ff:ff
3: genev_sys_6081: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65000 qdisc noqueue master ovs-system state UNKNOWN group default qlen 1000
    link/ether ea:6a:a7:01:dd:ca brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e86a:a7ff:fe01:ddca/64 scope link 
       valid_lft forever preferred_lft forever
4: br-int: <BROADCAST,MULTICAST> mtu 1400 qdisc noop state DOWN group default qlen 1000
    link/ether d2:ec:40:9f:5f:5a brd ff:ff:ff:ff:ff:ff
5: ovn-k8s-mp0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether de:43:d5:34:f5:e8 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.2/24 brd 10.244.0.255 scope global ovn-k8s-mp0
       valid_lft forever preferred_lft forever
    inet6 fe80::dc43:d5ff:fe34:f5e8/64 scope link 
       valid_lft forever preferred_lft forever
6: ovn-k8s-gw0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 0a:58:a9:fe:00:01 brd ff:ff:ff:ff:ff:ff
    inet 169.254.0.1/20 brd 169.254.15.255 scope global ovn-k8s-gw0
       valid_lft forever preferred_lft forever
    inet6 fe80::858:a9ff:fefe:1/64 scope link 
       valid_lft forever preferred_lft forever
7: br-local: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 02:83:90:8c:1b:43 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::83:90ff:fe8c:1b43/64 scope link 
       valid_lft forever preferred_lft forever
8: breth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.4/16 brd 172.18.255.255 scope global breth0
       valid_lft forever preferred_lft forever
    inet6 fc00:f853:ccd:e793::4/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:4/64 scope link 
       valid_lft forever preferred_lft forever
9: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ovs-system state UP group default 
    link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::42:acff:fe12:4/64 scope link 
       valid_lft forever preferred_lft forever
~~~

**Comment by andreaskaris** [comment]
When ovn-kubernetes is brought up, it checks if port eth0 is attached to br-ex. That test fails during initial setup (err != nil) and the `else if` condition is checked. `ovs-vsctl -- br-exists eth0` yields and error, and hence `util.NicToBridge(gwIntf)` is called which sets up the bridge.
~~~
175 func gatewayInitInternal(nodeName, gwIntf string, subnets []*net.IPNet, gwNextHops []net.IP, nodeAnnotator kube.Annotator) (
176         string, string, net.HardwareAddr, []*net.IPNet, error) {
177 
178         var bridgeName string
179         var uplinkName string
180         var brCreated bool
181         var err error
182 
183         if bridgeName, _, err = util.RunOVSVsctl("--", "port-to-br", gwIntf); err == nil {
184                 // This is an OVS bridge's internal port
185                 uplinkName, err = util.GetNicName(bridgeName)
186                 if err != nil {
187                         return bridgeName, uplinkName, nil, nil, err
188                 }
189         } else if _, _, err := util.RunOVSVsctl("--", "br-exists", gwIntf); err != nil {
190                 // This is not a OVS bridge. We need to create a OVS bridge
191                 // and add cluster.GatewayIntf as a port of that bridge.
192                 bridgeName, err = util.NicToBridge(gwIntf)
193                 if err != nil {
194                         return bridgeName, uplinkName, nil, nil, fmt.Errorf("failed to convert %s to OVS bridge: %v", gwIntf, err)
195                 }
196                 uplinkName = gwIntf
197                 gwIntf = bridgeName
198                 brCreated = true
199         } else {
200                 // gateway interface is an OVS bridge
201                 uplinkName, err = getIntfName(gwIntf)
202                 if err != nil {
203                         return bridgeName, uplinkName, nil, nil, err
204                 }
205                 bridgeName = gwIntf
206         }
207 
~~~

The problem on the reboot is that the IP address lands on eth0 again but now the first check yields `err == nil` due to:
~~~
sh-5.0# ovs-vsctl -- port-to-br eth0
breth0
~~~

And thus, the Nic is not remapped to the bridge.

**Comment by andreaskaris** [comment]
I begin to believe that there is a bug in the logic here.
~~~
176 func gatewayInitInternal(nodeName, gwIntf string, subnets []*net.IPNet, gwNextHops []net.IP, nodeAnnotator kube.Annotator) (
(...)
187         if bridgeName, _, err = util.RunOVSVsctl("--", "port-to-br", gwIntf); err == nil {
188                 // This is an OVS bridge's internal port
189                 uplinkName, err = util.GetNicName(bridgeName)
190                 if err != nil {
191                         return bridgeName, uplinkName, nil, nil, err
192                 }
193         } else if _, _, err := util.RunOVSVsctl("--", "br-exists", gwIntf); err != nil {
194                 // This is not a OVS bridge. We need to create a OVS bridge
195                 // and add cluster.GatewayIntf as a port of that bridge.
196                 bridgeName, err = util.NicToBridge(gwIntf)
197                 if err != nil {
198                         return bridgeName, uplinkName, nil, nil, fmt.Errorf("failed to convert %s to OVS bridge: %v", gwIntf, err)
199                 }
200                 uplinkName = gwIntf
201                 gwIntf = bridgeName
202                 brCreated = true
203         } else {
204                 // gateway interface is an OVS bridge
205                 uplinkName, err = getIntfName(gwIntf)
206                 if err != nil {
207                         return bridgeName, uplinkName, nil, nil, err
208                 }
209                 bridgeName = gwIntf
210         }
~~~

I do not see the benefit of the first `if` condition unless we migrate the IP address and default route to that gwIntf's bridge.

3 possible conditions come to mind:

a) the default gateway port is *not* a bridge but it is enslaved to an OVS bridge, but that OVS bridge does not hold the IP address and the gateway
In that case, run non-existing method util.MigrateIpAndRoutingToBridge(gwIntf, bridgeName)
b) the default gateway port is *not* a bridge and it is *not* part of an OVS bridge
In that case, run util.NicToBridge(gwIntf)
c) The default gateway port *is* already an OVS bridge 

Also, in the kind.sh setup script itself, we must make this here permanent and also _rename_ that method, because the method *enables* ipv6 contrary to its name:
~~~
docker_disable_ipv6() {
  # Docker disables IPv6 globally inside containers except in the eth0 interface.
  # Kind enables IPv6 globally the containers ONLY for dual-stack and IPv6 deployments.
  # Ovnkube-node tries to move all global addresses from the gateway interface to the
  # bridge interface it creates. This breaks on KIND with IPv4 only deployments, because the new
  # internal bridge has IPv6 disable and can't move the IPv6 from the eth0 interface.
  # We can enable IPv6 always in the container, since the docker setup with IPv4 only
  # is not very common.
  KIND_NODES=$(kind get nodes --name "${KIND_CLUSTER_NAME}")
  for n in $KIND_NODES; do
    docker exec "$n" sysctl net.ipv6.conf.all.disable_ipv6=0
    docker exec "$n" sysctl net.ipv6.conf.all.forwarding=1
  done
}
~~~

If we do not make the aforementioned changes permanent, ovnkube will not be able to migrate the IPv6 addresses:
~~~
root@ovn-control-plane:/# ip -6 a a fc00:f853:ccd:e793::3/64 dev breth0
RTNETLINK answers: Permission denied
~~~

And as a consequence, NicToBridge / MigrateIpAndRoutingToBridge will fail upon migration of the IPv6 address and then it will fail upon migration of the route, too.

I also do not like the fact that saveIPAddress will fail hard and early on the first IP which it cannot migrate, and saveRoute does the same. There's a risk (as illustrated) that all IPv4 addresses are migrated, then migration on IPv6 fails, and yet this gives up before migrating the IPv4 routes.
We should migrate as much as we can instead of failing early on the first obstacle that we encounter. We can then throw an error after that with all errors combined, perhaps. Or, we could migrate IPv4 addresses, then IPv4 routes, then IPv6 addresses, then IPv6 routes. Something like that.

**Comment by andreaskaris** [comment]
I'm currently working on this in https://github.com/andreaskaris/ovn-kubernetes/commit/c3a2aff9124a2616e7160ae3015ba77ecad727c0 , I'll submit the pull request when ready (and if everything works out as planned)
