### ISSUE TITLE
you can read my readme instead of offical readme file

### ISSUE THREAD

**Issue by sccblue** [ovn-org/ovn-kubernetes#2120]
the ovn-kubernetes not provide the right envirement to build the image , binary, ovs , ovn and so on
you can read my readme instead of offical readme file
https://github.com/sccblue/ovn-kubernetes

**Comment by LYTzeng** [comment]
This saved my day! Thank you!
For those who would like to build OVN debian packages, this can't be done because [OVN packages needs to be split from OVS](https://github.com/ovn-org/ovn/blob/master/Documentation/intro/install/debian.rst) ,unless we wait for further updates but I rather build rpm packages instead.

**Comment by sccblue** [comment]
Thanks for your affirmation.

**Comment by sccblue** [comment]
https://github.com/sccblue/ovn-kubernetes

**Comment by wangshuai199398** [comment]
有个问题能请教一下吗？ 我部署使用ipv6地址，起pod时不能i设置pv6地址，不知道大佬知道吗？
报错：failed to configure pod interface: failed to add IP addr 2000:1024:0:1::4/64 to eth0: permission denied
ipv4时可以的
