### ISSUE TITLE
New E2E Test Coverage: Upgrades

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#2132]
It would be great if we could have a job that runs which:
1. Deploys KIND using current origin/master HEAD
2. Launches some pods/traffic scenarios.
3. Builds a new docker image for current PR.
4. Rolls out new image for ovnkube-node daemonset.
5. Rolls out new image for ovnkube-master daemonset (workers need to upgrade before masters)
6. Runs traffic on the previously created pods, verify paths work after upgrade.
7. Verify no crashes.

**Comment by trozet** [comment]
@jluhrsen FYI

**Comment by kedark3** [comment]
Expressing my interest: I would like to give this a shot, if I can spare some time.  :smile:

**Comment by kedark3** [comment]
@trozet Can we expand step 3 mentioned above in two substeps as follows?
3a. Build new binaries from the current PR
3b. Build new docker images that use those binaries

Also, I see step 4 and 5 talk about node and master daemonsets, but don't we also need to DB and OVS related daemonsets? Trying to gather more info. 
And the best way to develop and tests would be to create a Draft PR so that I could leverage GitHub actions, right? 
Thanks.

**Comment by tssurya** [comment]
Fixed as part of https://github.com/ovn-org/ovn-kubernetes/pull/2186
