### ISSUE TITLE
flakey test: Informer Event Handler Tests adds existing pod and processes an update event 

### ISSUE THREAD

**Issue by jcaamano** [ovn-org/ovn-kubernetes#3946]
Observed: 
https://github.com/ovn-org/ovn-kubernetes/actions/runs/6385484874/job/17330329830
https://github.com/ovn-org/ovn-kubernetes/actions/runs/6366994650/job/17285200687

**Comment by flavio-fernandes** [comment]
Also failed here: https://github.com/ovn-org/ovn-kubernetes/actions/runs/6539650928/job/17758161887?pr=3963

```
 Informer Event Handler Tests 
  adds existing pod and processes an update event
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:202
I1016 22:01:40.604786   22867 informer.go:203] Starting test informer queue
I1016 22:01:40.605265   22867 informer.go:205] Waiting for test informer caches to sync
I1016 22:01:40.605412   22867 informer.go:211] Starting 1 test queue workers
I1016 22:01:40.605456   22867 informer.go:222] Started test queue workers
I1016 22:01:40.605542   22867 informer.go:319] Successfully synced 'test/foo'
I1016 22:01:41.708897   22867 informer.go:226] Shutting down test queue workers
I1016 22:01:41.708979   22867 informer.go:229] Shut down test queue workers

• Failure [1.106 seconds]
Informer Event Handler Tests
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:54
  adds existing pod and processes an update event [It]
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:202

  Timed out after 1.000s.
  adds
  Expected
      <int32>: 1
  to equal
      <int32>: 2

  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:281
  ```

**Comment by trozet** [comment]
Seen another instance here:
https://github.com/ovn-org/ovn-kubernetes/actions/runs/6539650928/job/17758161887?pr=3963

#3963

**Comment by martinkennelly** [comment]
Wont get to it for another 2 weeks at least. If anyones interested, please take it as I havent started yet.

**Comment by martinkennelly** [comment]
What i learned from Jordi:
* "the queue was notified of the event, but the informer, from which the queue is fed, did not return the same object, but the old one" "I run the tests in an infinite loop, they eventually got caught by the bug and failed. The less cpu usage, the less ratio of failures until I got a single test loop to run for 12h without failure"
* Jordi/Nadia can reproduce this in a stressed env - "I tried with >50% cpu usage and I was able to reproduce it pretty consistently" "for each event, get the object from the informer and compare the resourceVersion: if the one from the informer is older than the one from the event then there you have it"
* Jordi doesnt know if this is test framework issue or an actual issue with informer/lister code since we are faking kube server

**Comment by flavio-fernandes** [comment]
This issue can be reproduced by doing this:
```
cd go-controller

while : ; do go test -mod=vendor -test.v \
-race  github.com/ovn-org/ovn-kubernetes/go-controller/pkg/informer -ginkgo.v \
-ginkgo.focus='adds existing pod and processes an update event' \
-ginkgo.reportFile /dev/null && echo ok || break ; sleep 1 ; done
```

The fix is posted in https://github.com/ovn-org/ovn-kubernetes/pull/4070

In a nutshell, this is an issue with the test, not the informer code. Worker may start
after informer's sync() is called, causing the add and update events to become a single add event.
