### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by josecastillolema** [ovn-org/ovn-kubernetes#4011]
Python 3.12 has dropped the **imp** module:

```
$ python --version
Python 3.12.0

$ ./kind.sh --install-cni-plugins --disable-snat-multiple-gws --multi-network-enable
...
+ kind_local_registry_port=5000
+ kind_local_registry_name=kind-registry
+ j2 /home/jose/dev/ovn-kubernetes/contrib/kind.yaml.j2 -o /home/jose/dev/ovn-kubernetes/contrib/kind-ovn.yaml
Traceback (most recent call last):
  File "/home/jose/.local/bin/j2", line 5, in <module>
    from j2cli import main
  File "/home/jose/.local/lib/python3.12/site-packages/j2cli/__init__.py", line 10, in <module>
    from j2cli.cli import main
  File "/home/jose/.local/lib/python3.12/site-packages/j2cli/cli.py", line 8, in <module>
    import imp, inspect
ModuleNotFoundError: No module named 'imp'
```

 Code has to migrate to from **imp** to **importlib**

**Comment by josecastillolema** [comment]
https://github.com/python/cpython/issues/104212

**Comment by josecastillolema** [comment]
It looks that the problem comes from the [j2](https://github.com/kolypto/j2cli) dependency: https://github.com/kolypto/j2cli/issues/80

**Comment by josecastillolema** [comment]
Looks like the solution is moving to [Jinjanator](https://pypi.org/project/jinjanator/)

**Comment by skitt** [comment]
In Submariner we [handled this](https://github.com/submariner-io/shipyard/pull/1466) by switching to `python3-jinja2-cli` with [a small wrapper](https://github.com/submariner-io/shipyard/pull/1466/files#diff-99e70fc196c5262b0b39978201efcc863562e1e776af88261232788f566d1247) (which could be avoided by changing the invocations to pipe the values instead of setting them in the environment).
