### ISSUE TITLE
ovn-kubernetes does not allow to configure a custom mac

### ISSUE THREAD

**Issue by alonSadan** [ovn-org/ovn-kubernetes#776]
will be nice to have the option to pass as an argument a custom mac address which will be allocated for the interface.

**Comment by booxter** [comment]
OK, let me expand because it sounds like perhaps Alon asked the project to come up with its own solution for hardware addresses, while in reality there is prior art in CNI plugins for the same.

The Network Plumbing working group of Kubernetes came up with a standard for network attachment definitions: https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ/edit

This document explains how additional networks can be attached to pods and is implemented by Multus CNI plugin. This document defines, among other things, the `mac` attribute that can be passed via `CNI_ARGS` into the plugin. If it's passed, then the plugin is supposed to enforce it for the prepared binding. This feature is already implemented in multiple CNI plugins (e.g. ovs-cni, sriov-cni), it can also be implemented not natively via `tuning` plugin chaining. Other projects like KubeVirt / kubemacpool rely on this attribute for some features to work.

It would be very helpful if OVN-Kubernetes plugin adds support for this attribute like other plugins did, so that we can use it in KubeVirt / kubemacpool environments.

Thank you for consideration.

**Comment by alonSadan** [comment]
Thank you @booxter  for the way better explanation to the issue.

**Comment by girishmg** [comment]
@booxter yes, this is my list of things to do.
