### ISSUE TITLE
ovnkube node should read chassis ID from OVS, not SBDB

### ISSUE THREAD

**Issue by dcbw** [ovn-org/ovn-kubernetes#791]
In https://github.com/ovn-org/ovn-kubernetes/commit/ea0c8916943a19622c82fca9d2e9faf87f2b00d2#diff-f3d7921613782ead56f50c8aa5df6d9eL36  (PR #719 ) I didn't understand how the chassis ID was handled and I switched the node from reading the chassis ID from OVS to reading it from the SBDB. That's wrong because the local ovn-controller writes the chassis ID to the SBDB so we already have it locally.

We revert that hunk and switch back to reading from OVS:

```
func getNodeChassisID() (string, error) {
	chassisID, stderr, err := RunOVSVsctl("--if-exists", "get",
		"Open_vSwitch", ".", "external_ids:system-id")
	if err != nil {
		logrus.Errorf("No system-id configured in the local host, "+
			"stderr: %q, error: %v", stderr, err)
		return "", err
	}
	if chassisID == "" {
		return "", fmt.Errorf("No system-id configured in the local host")
	}

	return chassisID, nil
}
```

**Comment by dcbw** [comment]
@mccv1r0

**Comment by dcbw** [comment]
@girishmg

**Comment by girishmg** [comment]
@dcbw this was done to enable moving L3 gateway creation to master. To create L3 gateway, we need to create a logical router and bind it to a chassis using that node's system-id. So, in the master we retrieve this from the OVN SB since that is the only way to get the chassis id for that node (or we use node annotations to retrieve the system-id).
