### ISSUE TITLE
Empty Services should be rejected by the node switch load balancer

### ISSUE THREAD

**Issue by dcbw** [ovn-org/ovn-kubernetes#928]
Kubernetes expects services without endpoints to reject connections rather than blackhole them. ovn-kubernetes currently removes service VIPs from the node switch service load balancer when they have no endpoints, which blackholes the connections.

Instead, a node switch ACL should be created to `reject` traffic to that Service VIP which will either RST for TCP or ICMP unreach for UDP.

**Comment by trozet** [comment]
@dcbw I started looking at this today, and have some questions regarding this and #927. It seems to me like the load-balancer should be kept regardless of if idling is happening or not and regardless of if OVNEmptyLbEvents is set to true. For example, I can create a k8s service, with no endpoints. That service/load-balancer should exist, whether or not I'm using idling. By the same token, I can add endpoints, and then remove those endpoints and the service should still also exist. Because of this behavior, I would expect the load-balancer to also be kept in these cases, but that doesn't seem to be the behavior introduced in #927. What am I missing?

Additionally, when the service is created with no selector (or selector with no endpoints), the reject ACL should also be applied. As long as the service exists, with no endpoints I think the reject ACL should be configured. Not just when services are idled. It seems though in your message on #927 you expect services that are unidled to time out, and that is the desired behavior...but I don't understand why.

**Comment by trozet** [comment]
After talking to @putnopvut I think we have a common thought that the behavior should be:
1. Any k8s service with no endpoints should always keep the OVN load balancer w/ VIP.
2. A reject ACL should be applied to any lb/service that has no endpoints, unless that svc is being idled (via idle label or using the OVNEmptyLbEvents option).

I think this will make the code cleaner and the behavior more consistent. Thoughts?

**Comment by danwinship** [comment]
That sounds right to me
