### ISSUE TITLE
Prow for ovn-kubernetes

### ISSUE THREAD

**Issue by russellb** [ovn-org/ovn-kubernetes#988]
I've noticed reviewers using prow commands out of convention on ovn-kube reviews, though we don't have prow running (yet?).  I'm running a prow server for https://metal3.io.  I'd be happy to turn it on for the ovn-kube repo if you'd like.  The only weird thing is you'd see @metal3-io-bot on ovn-kube reviews.

Thoughts?

**Comment by russellb** [comment]
@dcbw @danwinship @girishmg

**Comment by danwinship** [comment]
We want better automated CI but I'm not sure we especially care about the rest of prow all that much. And I'm assuming your offer doesn't come with AWS billing attached so we'd still have to figure that out. And we also need definitions of CI jobs since we want to test against plain k8s not OpenShift.

**Comment by russellb** [comment]
Yeah, it was mostly just to actually enable the PR automation that I saw people using already.

**Comment by dcbw** [comment]
@russellb I would love to have a Github check that just runs a basic 1 master 2 node Kube cluster with ovnkube and tries some basic connectivity. I was thinking about using KIND (Kubernetes in Docker) since that would potentially work with Travis, but I have no time to work on it. So if you have something that could run, that's better than nothing.

I (eg RH) can pay for AWS if we need to.

**Comment by russellb** [comment]
The metal3-io cluster is probably not a good fit to rely on for running real CI jobs.  If you can can budget for it, how about we spin up a cluster for ovn-kube on AWS?  I can help install and configure prow on it since I've done it twice on the metal3-io cluster.  Note that you also need a GCP account for object storage.  That's where job logs will go.

**Comment by girishmg** [comment]
@russellb having a separate prow instance for ovn-k8s will be ideal. Not only the bot names will be confusing but also if something needs to be fixed in the Prow itself, then you will not have to share the credentials with the ovn-kube contributors and such.

**Comment by russellb** [comment]
Feel free to close this issue, or leave it open to track getting a prow cluster set up for ovn-kube (or all of OVN?)

**Comment by trozet** [comment]
We now have KIND OVN deployments for CI  with E2E testing, using travis/GitHub Actions. Do we still need this?
